name: bird
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - python
  - altair
  - plotly
  - rasterio
  - anywidget
  - shinywidgets
  - shiny
  - ipykernel
  - matplotlib
  - openpyxl
  - pyreadr
  - jupyterlab


