name: bird
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - python
  - altair
  - rasterio
  - anywidget
  - shinywidgets
  - shiny
  - ipykernel
  - matplotlib
  - openpyxl
  - gdal
  - polars
  - ipyleaflet
  - localtileserver
  - fastexcel
  - quarto
