project:
  type: website
  output-dir: _build

website:
  title: "Boreal Birds Documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: update_content.qmd
        text: Markdown Contents
      - section: "Reference"
        contents:
          - reference/index.qmd
          - auto: app

format:
  html:
    toc: true
    toc-depth: 3

quartodoc:
  dir: reference
  package: app
  
  sections:
    - title: Core Modules
      desc: Modules for data loading and UI components
      contents:
        # - modules.bird
        - shared
        - components
        - icons
        
    - title: Server Logic
      desc: Backend server modules for the dashboard.
      contents:
        - server.server_v5
        
    - title: UI Components
      desc: Frontend interface and layout modules.
      contents:
        - ui.sidebar
        - ui.welcome
        - ui.methods
        - ui.landbirds_v4
        - ui.landbirds_v5
        - ui.model_access