---
title: "Markdown Contents"
page-layout: full
---

# General Contents

::: {.list-table}

- - Markdown files
  - Description
  - Reference

- - `welcome.md`
  - content for the welcome main tab
  - `app/content/welcome.py`

- - `announcements.md`
  - content for any short-term notices
  - `app/content/welcome.py`

- - `tools.md`
  - location for externally available materials
  - `app/content/model_access.py`

- - `citing.md`
  - instructions on how to cite the model results
  - `app/ui/model_access.py`

:::

# Methods (see `app/content/methods.py`)


::: {.list-table}

- - Files
  - Description

- - `methods-intro.md`
  - method introduction

- - `methods-sections.yaml`
  - yaml file that points to different markdown files for methods accordion listed below

:::

::: {.list-table}

- - Markdown Files
  - Description

- - `study-area.md`
  - Study Area

- - `data-and-subsampling.md`
  - Avian Data and Subsampling

- - `density-calibration-and-offsets.md`
  - Density Calibration, Detectability Offsets

- - `environmental-covariates.md`
  - Environmental Covariates

- - `model-building.md`
  - Model Building

- - `model-validation.md`
  - Model Validation

- - `bootstrap-averaging-prediction.md`
  - Bootstrap Averaging and Prediction

- - `density-maps.md`
  - Density Maps

- - `regional-population-estimates.md`
  - Regional Population Estimates

- - `landcover-density-estimates.md`
  - Land Cover Based Density Estimates

- - `data-availability.md`
  - Data Availability

:::